name: MagicBattle
author: RandalSix
main: com.github.ctirpak.magicbattle.MagicBattle
version: 1.0.3
dscription: Magic Battle Plugin
api-version: 1.14

commands:
    magicbattle:
        usage: /<command> <args> [opt args]
        aliases: [mb]
        description: MagicBattle command!
    