name: MagicBattle
author: RandalSix
main: com.github.ctirpak.magicbattle.MagicBattle
version: 1.0
dscription: Magic Battle Plugin
api-version: 1.14

commands:
  hello:
    usage: /<command>
    aliases: [hello, helloworld, hw]
    description: Sends the player a hello message
    